// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getCookieDomain } from '@/utils/subdomain';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate required environment variables
if (!SUPABASE_URL) {
  console.error('[SUPABASE] Missing environment variable: VITE_SUPABASE_URL');
  throw new Error('Supabase configuration error: Missing VITE_SUPABASE_URL');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error('[SUPABASE] Missing environment variable: VITE_SUPABASE_PUBLISHABLE_KEY');
  throw new Error('Supabase configuration error: Missing VITE_SUPABASE_PUBLISHABLE_KEY');
}

const domain = getCookieDomain();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Custom storage to share sessions across subdomains
const cookieStorage = {
  getItem: (key: string) => {
    try {
      const cookies = document.cookie.split(';');
      for (const cookie of cookies) {
        const [name, value] = cookie.trim().split('=');
        if (name === key) return decodeURIComponent(value);
      }
      return localStorage.getItem(key); // Fallback to localStorage
    } catch (err) {
      console.error('[SUPABASE] Storage getItem error:', err);
      return null;
    }
  },
  setItem: (key: string, value: string) => {
    try {
      const secure = window.location.protocol === 'https:' ? 'Secure;' : '';
      const domainStr = domain ? `Domain=${domain};` : '';
      // Set cookie for subdomain sharing
      document.cookie = `${key}=${encodeURIComponent(value)}; ${domainStr} Path=/; SameSite=Lax; ${secure}`;
      // Also keep in localStorage for resilience
      localStorage.setItem(key, value);
    } catch (err) {
      console.error('[SUPABASE] Storage setItem error:', err);
    }
  },
  removeItem: (key: string) => {
    try {
      const domainStr = domain ? `Domain=${domain};` : '';
      document.cookie = `${key}=; ${domainStr} Path=/; Max-Age=0; SameSite=Lax;`;
      localStorage.removeItem(key);
    } catch (err) {
      console.error('[SUPABASE] Storage removeItem error:', err);
    }
  },
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: cookieStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});